export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const EDIT_SERVICE_ID = 'EDIT_SERVICE_ID';
export const BUTTON_EDIT_SERVICE = 'BUTTON_EDIT_SERVICE';
export const FILTERING_SERVICE = 'FILTERING_SERVICE';